version: '3.3'

services:
  nodejs:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   - MONGO_USERNAME=$MONGO_USERNAME
    #   - MONGO_PASSWORD=$MONGO_PASSWORD
    #   - MONGO_HOSTNAME=db
    #   - MONGO_PORT=$MONGO_PORT
    #   - MONGO_DB=$MONGO_DB
    ports: 
      - "4041:4041"
    networks:
      - app-network
    # command: db:27017
    command: node server.js

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    # env_file: .env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  
  sqldb:
    image: mysql:5.7
    container_name: sqldb
    restart: unless-stopped
    # env_file: .env
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=cryptwallet
      - MYSQL_ROOT_PASSWORD=root
    volumes:     
        - sqldbdata:/data/sqldb
    networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  sqldbdata:
